# Generated by Django 3.2.7 on 2021-10-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='line_total',
            field=models.FloatField(null=True),
        ),
    ]
