# Generated by Django 3.2.7 on 2021-10-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_orderline_line_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default.png', upload_to='products/', verbose_name='Image'),
        ),
    ]
