# Generated by Django 3.2.7 on 2021-10-13 20:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default.png', upload_to=api.models.upload_to, verbose_name='Image'),
        ),
    ]
